openapi: 3.0.0
info:
  title: OFDM Parallel Chunk Transmission Protocol
  version: 1.0.0
  description: Protocol for transmitting BitTorrent chunks in parallel across OFDM subcarriers

paths:
  /transmit/parallel-chunk-frame:
    post:
      summary: Transmit parallel chunk frame via OFDM
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParallelChunkFrame'
      responses:
        '200':
          description: Frame transmitted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransmissionResult'
        '400':
          description: Invalid frame configuration
        '503':
          description: Insufficient healthy carriers

  /allocate/chunks-to-carriers:
    post:
      summary: Allocate chunks to available subcarriers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                chunks:
                  type: array
                  items:
                    $ref: '#/components/schemas/ChunkRequest'
                carrierHealth:
                  type: array
                  items:
                    $ref: '#/components/schemas/CarrierHealthMetric'
      responses:
        '200':
          description: Allocation successful
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChunkAllocation'

  /monitor/carrier-health:
    get:
      summary: Get current carrier health metrics
      responses:
        '200':
          description: Carrier health status
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CarrierHealthMetric'

  /configure/ofdm:
    put:
      summary: Update OFDM configuration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OFDMConfiguration'
      responses:
        '200':
          description: Configuration updated
        '400':
          description: Invalid configuration parameters

components:
  schemas:
    ParallelChunkFrame:
      type: object
      required:
        - frameId
        - timestamp
        - chunkAllocations
        - pilotTones
      properties:
        frameId:
          type: integer
          minimum: 0
        timestamp:
          type: integer
          format: int64
        symbolDuration:
          type: number
          default: 23.2
        chunkAllocations:
          type: array
          maxItems: 48
          items:
            $ref: '#/components/schemas/ChunkAllocation'
        pilotTones:
          type: array
          minItems: 5
          maxItems: 5
          items:
            type: object
            properties:
              index:
                type: integer
              value:
                type: number
        cyclicPrefix:
          type: integer
          default: 64

    ChunkAllocation:
      type: object
      required:
        - chunkId
        - chunkIndex
        - subcarriers
        - modulation
        - priority
      properties:
        chunkId:
          type: string
          pattern: '^[a-f0-9]{64}$'
        chunkIndex:
          type: integer
          minimum: 0
        subcarriers:
          type: array
          minItems: 1
          maxItems: 4
          items:
            type: integer
            minimum: 0
            maximum: 47
        modulation:
          type: string
          enum: [BPSK, QPSK, 16QAM]
        priority:
          type: integer
          minimum: 0
          maximum: 10
        retryCount:
          type: integer
          default: 0

    CarrierHealthMetric:
      type: object
      required:
        - carrierId
        - frequency
        - snr
        - enabled
      properties:
        carrierId:
          type: integer
          minimum: 0
          maximum: 47
        frequency:
          type: number
        snr:
          type: number
          minimum: -10
          maximum: 40
        ber:
          type: number
          minimum: 0
          maximum: 1
        enabled:
          type: boolean
        lastUpdate:
          type: integer
          format: int64

    ChunkRequest:
      type: object
      required:
        - chunkId
        - chunkIndex
        - priority
        - rarity
      properties:
        chunkId:
          type: string
        chunkIndex:
          type: integer
        priority:
          type: integer
          minimum: 0
          maximum: 10
        rarity:
          type: number
          minimum: 0
          maximum: 1

    OFDMConfiguration:
      type: object
      required:
        - sampleRate
        - fftSize
        - numSubcarriers
        - bandwidth
      properties:
        sampleRate:
          type: integer
          default: 11025
        fftSize:
          type: integer
          enum: [128, 256, 512, 1024]
          default: 256
        numSubcarriers:
          type: integer
          maximum: 48
          default: 48
        subcarrierSpacing:
          type: number
          default: 43
        symbolDuration:
          type: number
          default: 23.2
        cyclicPrefixRatio:
          type: number
          default: 0.25
        bandwidth:
          type: integer
          maximum: 2800

    TransmissionResult:
      type: object
      properties:
        frameId:
          type: integer
        successfulChunks:
          type: integer
        failedChunks:
          type: integer
        throughput:
          type: number
        activeCarriers:
          type: integer
        duration:
          type: number